"""Add privacy settings columns

Revision ID: 4a90ded406fa
Revises: 5409d4a66669
Create Date: 2024-12-13 23:59:19.289991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a90ded406fa'
down_revision = '5409d4a66669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epsilon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_level', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_record', schema=None) as batch_op:
        batch_op.drop_column('noise_level')
        batch_op.drop_column('epsilon')

    # ### end Alembic commands ###
