"""Add file size and type columns

Revision ID: 5409d4a66669
Revises: f1762149ff55
Create Date: 2024-12-13 23:34:58.299980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5409d4a66669'
down_revision = 'f1762149ff55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('data_type')
        batch_op.drop_column('is_encrypted')
        batch_op.drop_column('is_private')
        batch_op.drop_column('noise_level')
        batch_op.drop_column('encryption_status')
        batch_op.drop_column('epsilon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epsilon', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('encryption_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('noise_level', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_encrypted', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('data_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('file_size')

    # ### end Alembic commands ###
