"""Add public sharing fields to DataShare

Revision ID: f1762149ff55
Revises: 096920cc44d2
Create Date: 2024-12-13 22:27:48.858499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1762149ff55'
down_revision = '096920cc44d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public_link', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('download_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('download_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_address', sa.String(length=120), nullable=True))
        batch_op.alter_column('shared_with_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_share', schema=None) as batch_op:
        batch_op.alter_column('shared_with_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('email_address')
        batch_op.drop_column('download_count')
        batch_op.drop_column('download_limit')
        batch_op.drop_column('is_public_link')

    # ### end Alembic commands ###
